# Generated by Django 6.0.5 on 2026-05-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique ingredient or stock item name.', max_length=150, unique=True)),
                ('unit', models.CharField(help_text='Stock unit, for example kg, litres, or pieces.', max_length=50)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, help_text='Current quantity available in stock.', max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, help_text='Minimum quantity allowed before restocking is needed.', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Purchase cost for one stock unit.', max_digits=8)),
                ('last_restocked', models.DateTimeField(blank=True, help_text='Date and time this item was last restocked.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this inventory item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this inventory item was last updated.')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Quantity of this ingredient needed for one menu item.', max_digits=8)),
                ('ingredient', models.ForeignKey(help_text='Inventory item required by the menu item.', on_delete=django.db.models.deletion.PROTECT, related_name='menu_item_links', to='inventory.inventoryitem')),
                ('menu_item', models.ForeignKey(help_text='Menu item that uses this ingredient.', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'menu item ingredient',
                'verbose_name_plural': 'menu item ingredients',
                'ordering': ['menu_item__name', 'ingredient__name'],
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
