from django.contrib import admin

from .models import Category, Event, Registration


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = (
        "name",
        "created_at",
    )
    search_fields = ("name",)
    readonly_fields = ("created_at",)


@admin.register(Event)
class EventAdmin(admin.ModelAdmin):
    list_display = (
        "title",
        "organizer",
        "category",
        "start_datetime",
        "capacity",
        "current_registrations",
        "status",
    )
    list_filter = (
        "status",
        "category",
        "start_datetime",
    )
    search_fields = (
        "title",
        "organizer__email",
        "location",
    )
    readonly_fields = (
        "created_at",
        "updated_at",
        "current_registrations",
        "spots_left",
    )

    @admin.display(description="Current registrations")
    def current_registrations(self, obj):
        return obj.current_registrations

    @admin.display(description="Spots left")
    def spots_left(self, obj):
        return obj.spots_left


@admin.register(Registration)
class RegistrationAdmin(admin.ModelAdmin):
    list_display = (
        "ticket_number",
        "user",
        "event",
        "status",
        "registered_at",
    )
    list_filter = (
        "status",
        "event",
        "registered_at",
    )
    search_fields = (
        "ticket_number",
        "user__email",
        "event__title",
    )
    readonly_fields = (
        "ticket_number",
        "registered_at",
    )


# ============================================================
# REVIEW — READ THIS THEN DELETE FROM THIS LINE TO THE END
# ============================================================
#
# What each class or function does and why it was written that way
#
# CategoryAdmin controls how Category records appear in the Django admin. It
# shows the name and creation date, allows searching by name, and makes
# created_at read-only because Django fills that timestamp automatically.
#
# EventAdmin controls how Event records appear in the Django admin. The list
# page shows the event title, organizer, category, start time, capacity, current
# registration count, and status so admins can scan event health quickly.
#
# EventAdmin.current_registrations is an admin display method. It reads the
# current_registrations property from the Event model and shows it as a column
# and read-only field in the admin.
#
# EventAdmin.spots_left is an admin display method. It reads the spots_left
# property from the Event model and shows how many confirmed places remain.
#
# RegistrationAdmin controls how Registration records appear in the Django
# admin. It shows the ticket number, user, event, status, and registration time
# because those fields identify each booking clearly.
#
# Important decisions that were made and why
#
# EventAdmin uses display methods for current_registrations and spots_left
# because those values are calculated properties, not database columns.
#
# created_at, updated_at, current_registrations, spots_left, ticket_number, and
# registered_at are read-only because they are generated by the system or
# calculated from existing data.
#
# search_fields uses relationship lookups like organizer__email, user__email,
# and event__title so admins can search across related models.
#
# The admin registrations use @admin.register(...) because that style keeps each
# model connected directly to its admin class.
#
# What you should read and understand before you review the code
#
# Read Django ModelAdmin options: list_display, list_filter, search_fields, and
# readonly_fields.
#
# Read Django admin display methods and the @admin.display decorator.
#
# Read Django relationship lookups using double underscores, such as
# user__email and event__title.
#
# Read the Event model properties so you understand why current_registrations
# and spots_left are calculated instead of saved as separate fields.
#
# ============================================================
# END OF REVIEW
# ============================================================
