# Generated by Django 6.0.5 on 2026-05-06 18:54

import shortener.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shortener.models.UserManager()),
            ],
        ),
    ]
