# Generated by Django 6.0.5 on 2026-05-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter written by the candidate.', null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Reviewing'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='APPLIED', help_text='Current review status of this application.', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this application was submitted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this application was last updated.')),
                ('candidate', models.ForeignKey(help_text='Candidate user who submitted this application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job listing this application belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Private note visible to employers or staff.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this note was created.')),
                ('application', models.ForeignKey(help_text='Application this private note belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
                ('created_by', models.ForeignKey(help_text='Employer or staff user who created this note.', on_delete=django.db.models.deletion.PROTECT, related_name='application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application note',
                'verbose_name_plural': 'application notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resume title, such as My Software Dev Resume.', max_length=150)),
                ('file', models.FileField(help_text='Uploaded resume file.', upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this resume was uploaded.')),
                ('is_primary', models.BooleanField(default=False, help_text="Shows whether this is the candidate's main resume.")),
                ('candidate', models.ForeignKey(help_text='Candidate user who uploaded this resume.', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'ordering': ['-uploaded_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, help_text='Optional resume attached to this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.resume'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
