# Generated by Django 6.0.5 on 2026-05-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], default='RECEIVED', help_text='Current preparation and service status of the order.', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount calculated from all order items.', max_digits=10)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine in'), ('TAKEAWAY', 'Takeaway')], default='DINE_IN', help_text='Whether the order is dine-in or takeaway.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this order was last updated.')),
                ('customer', models.ForeignKey(help_text='Customer who placed this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, help_text='Optional table for dine-in orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservations.restauranttable')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of this menu item ordered.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Menu item price at the time of ordering.', max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Line total calculated from quantity and unit price.', max_digits=10)),
                ('menu_item', models.ForeignKey(help_text='Menu item ordered by the customer.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(help_text='Order that this line item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
