# Generated by Django 6.0.5 on 2026-05-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique category name shown on the menu.', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Short description of the category.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear earlier in the menu.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this category is visible to customers.')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu item shown to customers.', max_length=150)),
                ('description', models.TextField(help_text='Customer-facing description of the menu item.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price of the menu item.', max_digits=8)),
                ('is_available', models.BooleanField(default=True, help_text='Controls whether customers can currently order this item.')),
                ('image', models.ImageField(blank=True, help_text='Optional photo of the menu item.', null=True, upload_to='menu_items/')),
                ('preparation_time', models.PositiveIntegerField(help_text='Estimated preparation time in minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this menu item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this menu item was last updated.')),
                ('category', models.ForeignKey(help_text='Category where this menu item appears.', on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='menu.category')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
