# Generated by Django 6.0.5 on 2026-05-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(help_text='Unique table number used by staff.', unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests this table can seat.')),
                ('location', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('PRIVATE', 'Private')], help_text='Restaurant area where this table is located.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this table can be used for bookings.')),
            ],
            options={
                'verbose_name': 'restaurant table',
                'verbose_name_plural': 'restaurant tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_datetime', models.DateTimeField(help_text='Date and time the reservation begins.')),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='Expected reservation duration in minutes.')),
                ('party_size', models.PositiveIntegerField(help_text='Number of guests included in the reservation.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current reservation status.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or special requests for the reservation.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this reservation was created.')),
                ('customer', models.ForeignKey(help_text='Customer who made this reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(help_text='Table assigned to this reservation.', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.restauranttable')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['-reservation_datetime'],
            },
        ),
    ]
