# Generated by Django 6.0.2 on 2026-05-22 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique category name used to group similar events.', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed explanation of what this category contains.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this category was created.')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Public title of the event.', max_length=255)),
                ('description', models.TextField(help_text='Full details about the event.')),
                ('location', models.CharField(help_text='Physical or online location where the event will happen.', max_length=255)),
                ('start_datetime', models.DateTimeField(help_text='Date and time when the event starts.')),
                ('end_datetime', models.DateTimeField(help_text='Date and time when the event ends.')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of confirmed registrations allowed.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PUBLISHED', help_text='Current publication and lifecycle status of the event.', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional image used to represent the event.', null=True, upload_to='events/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this event was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this event was last updated.')),
                ('category', models.ForeignKey(help_text='Category this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.category')),
                ('organizer', models.ForeignKey(help_text='User responsible for creating and managing this event.', on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('WAITLISTED', 'Waitlisted')], default='CONFIRMED', help_text='Current status of this registration.', max_length=20)),
                ('ticket_number', models.CharField(help_text='Unique ticket identifier for this registration.', max_length=20, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user registered.')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Date and time when the registration was cancelled.', null=True)),
                ('event', models.ForeignKey(help_text='Event that the user registered for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(help_text='User who registered for the event.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
