# Generated by Django 6.0.5 on 2026-05-27 05:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Unique email address used to sign in.', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('EMPLOYER', 'Employer'), ('CANDIDATE', 'Candidate')], default='CANDIDATE', help_text='User role inside the job board platform.', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Optional contact phone number.', max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short user biography shown on the profile.', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional profile picture for the user.', null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Short professional headline, such as Senior Django Dev.', max_length=150)),
                ('skills', models.TextField(help_text='Comma-separated list of candidate skills.')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Total years of professional experience.')),
                ('education', models.TextField(blank=True, help_text='Optional education summary.', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Optional LinkedIn profile URL.', null=True)),
                ('portfolio_url', models.URLField(blank=True, help_text='Optional portfolio or personal website URL.', null=True)),
                ('user', models.OneToOneField(help_text='Candidate user who owns this professional profile.', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Unique company name shown on job listings.', max_length=150, unique=True)),
                ('company_description', models.TextField(help_text='Overview of the company and what it does.')),
                ('website', models.URLField(blank=True, help_text='Optional company website URL.', null=True)),
                ('industry', models.CharField(help_text='Primary industry where the company operates.', max_length=100)),
                ('company_size', models.CharField(choices=[('STARTUP', 'Startup'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('ENTERPRISE', 'Enterprise')], help_text='Approximate size of the company.', max_length=20)),
                ('location', models.CharField(help_text='Main company location.', max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='Optional company logo image.', null=True, upload_to='company_logos/')),
                ('verified', models.BooleanField(default=False, help_text='Shows whether admins have verified this employer.')),
                ('user', models.OneToOneField(help_text='Employer user who owns this company profile.', on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employer profile',
                'verbose_name_plural': 'employer profiles',
                'ordering': ['company_name'],
            },
        ),
    ]
