# Generated by Django 6.0.5 on 2026-05-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique job category name.', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Short description of jobs in this category.')),
            ],
            options={
                'verbose_name': 'job category',
                'verbose_name_plural': 'job categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Public job title shown to candidates.', max_length=150)),
                ('description', models.TextField(help_text='Detailed job description.')),
                ('requirements', models.TextField(help_text='Skills, qualifications, and responsibilities required.')),
                ('location', models.CharField(help_text='Job location or headquarters.', max_length=150)),
                ('is_remote', models.BooleanField(default=False, help_text='Shows whether this job can be done remotely.')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], help_text='Employment type for this job.', max_length=20)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('EXECUTIVE', 'Executive')], help_text='Experience level expected for this role.', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum salary for this job.', max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum salary for this job.', max_digits=12, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Shows whether this job should be highlighted.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', help_text='Publication status of this job listing.', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times candidates have viewed this listing.')),
                ('application_deadline', models.DateField(blank=True, help_text='Optional final date candidates can apply.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this job was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this job was last updated.')),
                ('category', models.ForeignKey(help_text='Category this job belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='job_listings', to='jobs.jobcategory')),
                ('employer', models.ForeignKey(help_text='Employer user who posted this job.', on_delete=django.db.models.deletion.PROTECT, related_name='job_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job listing',
                'verbose_name_plural': 'job listings',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
